baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = "Jonathan's Blog"
theme = "johz"
copyright = "This work is licensed under CC BY-SA 4.0"

# disableKinds = ["term"]

[taxonomies]
tag = 'tags'

[menus]
[[menus.main]]
name = "About"
pageRef = "/about"
weight = 10

[[menus.main]]
name = "Github"
url = "https://github.com/MrJohz/"
weight = 20

[[menus.main]]
name = "Light/Dark"
url = "javascript:toggletheme()"
weight = 30


[markup]
[markup.highlight]
noClasses = false
