[[discussions]]
title = "Why Test?"
url = "https://lobste.rs/s/prowkp/why_test"
site = "Lobsters"
timestamp = 2024-06-25T12:14:58.000Z
comment_count = 15
score = 11

[[discussions]]
title = "Why Test?"
url = "https://news.ycombinator.com/item?id=40779593"
site = "Hacker News"
timestamp = 2024-06-24T19:12:58.000Z
comment_count = 0
score = 3
hidden = true

[[discussions]]
title = "Why Test?"
url = "https://www.reddit.com/r/programming/comments/1dnlnfr/why_test/"
site = "Reddit (/r/programming)"
timestamp = 2024-06-24T19:11:32.000Z
comment_count = 8
score = 0
hidden = true