[[discussions]]
title = "The Helix Text Editor (2024)"
url = "https://news.ycombinator.com/item?id=45166238"
site = "Hacker News"
timestamp = 2025-09-08T09:27:40.000Z
comment_count = 58

[[discussions]]
title = "Helix: Why (and How) I Use It"
url = "https://news.ycombinator.com/item?id=42422659"
site = "Hacker News"
timestamp = 2024-12-15T10:19:07.000Z
comment_count = 0
hidden = true

[[discussions]]
title = "Helix: Why (and How) I Use It"
url = "https://news.ycombinator.com/item?id=42415728"
site = "Hacker News"
timestamp = 2024-12-14T09:18:33.000Z
comment_count = 0
hidden = true

[[discussions]]
title = "Helix: Why (and How) I Use It"
url = "https://news.ycombinator.com/item?id=42410531"
site = "Hacker News"
timestamp = 2024-12-13T17:34:30.000Z
comment_count = 0
hidden = true

[[discussions]]
title = "Helix: Why (And How) I Use It"
url = "https://lobste.rs/s/i1xzas/helix_why_how_i_use_it"
site = "Lobsters"
timestamp = 2024-12-13T17:33:29.000Z
comment_count = 41

[[discussions]]
title = "I wrote a bit about Helix and how/why I've been using it"
url = "https://www.reddit.com/r/HelixEditor/comments/1hctxlj/i_wrote_a_bit_about_helix_and_howwhy_ive_been/"
site = "Reddit (/r/HelixEditor)"
timestamp = 2024-12-12T20:03:50.000Z
comment_count = 14