[[discussions]]
title = "Helix: Why (and How) I Use It"
url = "https://news.ycombinator.com/item?id=42410531"
site = "Hacker News"
timestamp = 2024-12-13T17:34:30.000Z
comment_count = 0
score = 1

[[discussions]]
title = "Helix: Why (And How) I Use It"
url = "https://lobste.rs/s/i1xzas/helix_why_how_i_use_it"
site = "Lobsters"
timestamp = 2024-12-13T17:33:29.000Z
comment_count = 11
score = 9