[[discussions]]
title = "Switching to BunnyCDN in Less Than 2 Hours"
url = "https://news.ycombinator.com/item?id=43330796"
site = "Hacker News"
timestamp = 2025-03-11T09:48:14.000Z
comment_count = 59
score = 120