[[discussions]]
title = "Switching to BunnyCDN in Less Than 2 Hours"
url = "https://www.reddit.com/r/hackernews/comments/1jbtjmc/switching_to_bunnycdn_in_less_than_2_hours/"
site = "Reddit (/r/hackernews)"
timestamp = 2025-03-15T12:00:03.000Z
comment_count = 1
score = 2

[[discussions]]
title = "Switching to BunnyCDN in Less Than 2 Hours"
url = "https://news.ycombinator.com/item?id=43330796"
site = "Hacker News"
timestamp = 2025-03-11T09:48:14.000Z
comment_count = 65
score = 124