[[discussions]]
title = "Why Are Jujutsu's ID Prefixes So Short?"
url = "https://news.ycombinator.com/item?id=43194600"
site = "Hacker News"
timestamp = 2025-02-27T14:19:40.000Z
comment_count = 0
score = 7

[[discussions]]
title = "Why are Jujutsu's ID Prefixes So Short?"
url = "https://lobste.rs/s/ww96mh/why_are_jujutsu_s_id_prefixes_so_short"
site = "Lobsters"
timestamp = 2025-02-27T14:16:38.000Z
comment_count = 0
score = 14