[[discussions]]
title = "This Overly Long Variable Name Could Have Been a Comment | Jonathan's Blog"
url = "https://www.reddit.com/r/programming/comments/1m223f5/this_overly_long_variable_name_could_have_been_a/"
site = "Reddit (/r/programming)"
timestamp = 2025-07-17T08:27:49.000Z
comment_count = 4

[[discussions]]
title = "Overly Long Variable Name Could Have Been a Comment"
url = "https://news.ycombinator.com/item?id=44474134"
site = "Hacker News"
timestamp = 2025-07-05T17:19:42.000Z
comment_count = 1
hidden = true

[[discussions]]
title = "Overly Long Variable Name Could Have Been a Comment"
url = "https://news.ycombinator.com/item?id=44455717"
site = "Hacker News"
timestamp = 2025-07-03T14:56:50.000Z
comment_count = 2

[[discussions]]
title = "Overly Long Variable Name Could Have Been a Comment"
url = "https://news.ycombinator.com/item?id=44446069"
site = "Hacker News"
timestamp = 2025-07-02T16:58:15.000Z
comment_count = 3

[[discussions]]
title = "This Overly Long Variable Name Could Have Been a Comment"
url = "https://lobste.rs/s/tnvcca/this_overly_long_variable_name_could_have"
site = "Lobsters"
timestamp = 2025-07-02T16:56:01.000Z
comment_count = 24