[[discussions]]
title = "New Disposable APIs in Javascript | Jonathan's Blog"
url = "https://www.reddit.com/r/javascript/comments/1h6ft6y/new_disposable_apis_in_javascript_jonathans_blog/"
site = "Reddit (/r/javascript)"
timestamp = 2024-12-04T13:20:17.000Z
comment_count = 13
score = 26

[[discussions]]
title = "New Disposable APIs in Javascript | Jonathan's Blog"
url = "https://www.reddit.com/r/ThePrimeagenReact/comments/1cq7lth/new_disposable_apis_in_javascript_jonathans_blog/"
site = "Reddit (/r/ThePrimeagenReact)"
timestamp = 2024-05-12T13:13:59.000Z
comment_count = 0
score = 1
hidden = true

[[discussions]]
title = "New Disposable APIs in JavaScript"
url = "https://news.ycombinator.com/item?id=40275139"
site = "Hacker News"
timestamp = 2024-05-06T14:31:28.000Z
comment_count = 0
score = 2
hidden = true

[[discussions]]
title = "The new disposable APIs in Javascript"
url = "https://www.reddit.com/r/programming/comments/1clc3pd/the_new_disposable_apis_in_javascript/"
site = "Reddit (/r/programming)"
timestamp = 2024-05-06T06:13:28.000Z
comment_count = 26
score = 97

[[discussions]]
title = "The new disposable APIs in Javascript"
url = "https://www.reddit.com/r/javascript/comments/1cky712/the_new_disposable_apis_in_javascript/"
site = "Reddit (/r/javascript)"
timestamp = 2024-05-05T18:43:41.000Z
comment_count = 27
score = 117