name: Update CDN

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update-comments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.141.0"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy to BunnyCDN
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: storage.bunnycdn.com
          username: ${{ secrets.STORAGE_NAME }}
          password: ${{ secrets.STORAGE_PASSWORD }}
          local-dir: "public/"
