name: Update Comments

on:
  push:
    branches: ["main"]

jobs:
  update-comments:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: cd scripts && pnpm install
      - run: cd scripts && pnpm run download-comments
      - run: git status
