name: Update Comments

on:
  schedule:
    - cron: "23 4,10,16,22 * * *"
  workflow_dispatch:

jobs:
  update-comments:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "scripts/pnpm-lock.yaml"
      - run: cd scripts && pnpm install --frozen-lockfile
      - run: cd scripts && pnpm run download-comments
        env:
          REDDIT_ID: ${{ secrets.RedditId }}
          REDDIT_SECRET: ${{ secrets.RedditSecret }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "[automated] Update discussions"
          branch: "update-discussions"
          title: "Update Discussions"
          assignees: "MrJohz"
          delete-branch: true
